### ISSUE TITLE
The security token included in the request is invalid.

### ISSUE THREAD

**Issue by septs** [kazimanzurrashid/aws-lambda-update-action#1]
![image](https://user-images.githubusercontent.com/3842474/100693077-1a702e00-33c7-11eb-8ff0-7ade0f4374ae.png)

My action:
```yaml
      - uses: kazimanzurrashid/aws-lambda-update-action@v1
        with:
          zip-file: ./bundle.zip
          lambda-name: telegram-personal-bot
          AWS_REGION: ap-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_ACCESS_KEY }}
```

Related discussion:
- https://stackoverflow.com/a/47098678
- https://github.com/99designs/aws-vault/issues/339#issuecomment-614713233
